TRAIN_DATA_PATH = './train.csv'
VAL_DATA_PATH = 'data/val.csv'
TOKENIZER_PATH = 'lib/model/tokenizer.pt'
CONFIG_BERT_PATH = 'lib/model/config_distil_rubert.json'
PRETRAINED_WEIGHTS_PATH = 'lib/model/bert_best_clf.pt'
BATCH_SIZE = 8
TRESHHOLD = 0.28537378

# TRAIN_DATA_PATH,
# VAL_DATA_PATH,
# TOKENIZER_PATH,
# TRANSFORMER_TOKENIZED_DATASET_PATH,
# CATBOOST_TOKENIZED_DATASET_PATH,
# CONFIG_BERT_PATH,
# PRETRAINED_WEIGHTS_PATH,
# BATCH_SIZE